[build]
  # 배포할 디렉토리를 설정합니다. 리액트 앱의 경우 일반적으로 빌드된 파일이 'build' 디렉토리에 있습니다.
  publish = "build"
  
  # 빌드 명령어를 설정합니다. create-react-app을 사용하는 경우 기본적으로 'npm run build'가 필요합니다.
  command = "npm run build"

[[redirects]]
  # SPA (Single Page Application)일 경우 모든 경로를 index.html로 리다이렉트할 수 있습니다.
  from = "/*"
  to = "/index.html"
  status = 200